### ISSUE TITLE
Provare nuovi temi

### ISSUE THREAD

**Issue by Radeox** [pdpfsug/wp_raga10#6]

**Comment by GiorgioPaoletti** [comment]
- Zerif Lite:
  https://downloads.wordpress.org/theme/zerif-lite.1.8.4.4.zip
- Ascent:
  https://downloads.wordpress.org/theme/ascent.2.0.3.zip
- Onetone:
  https://downloads.wordpress.org/theme/onetone.1.8.0.zip
- Lawveria Lite:
  https://downloads.wordpress.org/theme/lawyeria-lite.1.0.7.zip
- Metro CreativeX:
  https://downloads.wordpress.org/theme/metro-creativex.1.3.6.zip
- Nictitate:
  https://downloads.wordpress.org/theme/nictitate.1.1.4.zip
